source 'https://rubygems.org'

ruby '2.7.5'
gem 'fastlane'
gem 'ffi'
gem 'fastlane-plugin-load_json'
gem 'fastlane-plugin-rename_android_package'
gem 'fastlane-plugin-update_android_strings'
gem 'fastlane-plugin-versioning_android'
gem 'cocoapods', '~> 1.11', '>= 1.11.2'
