require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'core' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true
  )

  pod 'RNRate', :path => '../node_modules/react-native-rate'
  pod 'RNSensors', :path => '../node_modules/react-native-sensors'
  pod 'RNSound', :path => '../node_modules/react-native-sound'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'coreTests' do
    inherit! :complete
    # Pods for testing
  end

  use_flipper!()
  post_install do |installer|
    react_native_post_install(installer)
  end
end
