name: Deploy Android

on:
  push:
    branches: [master, ci-fastlane]

env:
  ANDROID_GOOGLE_KEY: { { secrets.ANDROID_GOOGLE_KEY } }
  ANDROID_KEYSTORE_PASSWORD: { { secrets.ANDROID_KEYSTORE_PASSWORD } }
  ANDROID_KEY_ALIAS: { { secrets.ANDROID_KEY_ALIAS } }
  ANDROID_KEY_PASSWORD: { { secrets.ANDROID_KEY_PASSWORD } }
  ANDROID_STORE_FILE_DEBUG: { { secrets.ANDROID_STORE_FILE_DEBUG } }
  ANDROID_STORE_FILE_RELEASE: { { secrets.ANDROID_STORE_FILE_RELEASE } }
  APP_CENTER_API: { { secrets.APP_CENTER_API } }
  FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD:
    { { secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD } }
  FASTLANE_GIT_TOKEN: { { secrets.FASTLANE_GIT_TOKEN } }
  IOS_APPLE_KEY: { { secrets.IOS_APPLE_KEY } }
  MAESTRO_CLOUD_API_KEY: { { secrets.MAESTRO_CLOUD_API_KEY } }
  MATCH_PASSWORD: { { secrets.MATCH_PASSWORD } }
  SLACK_URL: { { secrets.SLACK_URL } }

jobs:
  deploy-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install Node Dependencies
        run: yarn ci-install

      - name: Install Ruby Dependencies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true

      - name: Install Android Dependencies
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'zulu'
          cache: 'gradle'

      - name: Install Environment Variables
        run: yarn ci-env

      - name: Deploy Android
        uses: maierj/fastlane-action@v3.0.0
        with:
          lane: android deploy app:core method:beta

      - name: Deploy Tests
        uses: mobile-dev-inc/action-maestro-cloud@v1.2.3
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          app-file: android/app/build/outputs/apk/debug/app-debug.apk
