name: Deploy Package

on:
  push:
    branches: [master]

jobs:
  deploy-to-github-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6.0.2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
          registry-url: https://npm.pkg.github.com/
          scope: '@ethanneff'

      - name: Install Dependencies
        run: pnpm ci-install

      - name: Update Version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm ci-release

      - name: Deploy to Github Packages
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
