name: Deploy iOS

on:
  push:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  ANDROID_GOOGLE_KEY: ${{ secrets.ANDROID_GOOGLE_KEY }}
  ANDROID_STORE_FILE_DEBUG: ${{ secrets.ANDROID_STORE_FILE_DEBUG }}
  ANDROID_STORE_FILE_RELEASE: ${{ secrets.ANDROID_STORE_FILE_RELEASE }}
  # FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
  FASTLANE_GIT_TOKEN: ${{ secrets.FASTLANE_GIT_TOKEN }}
  FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
  IOS_APPLE_KEY: ${{ secrets.IOS_APPLE_KEY }}
  MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
  MATCH_KEYCHAIN_PASSWORD: ''
  SLACK_URL: ${{ secrets.SLACK_URL }}

jobs:
  deploy-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install node dependencies
        run: yarn ci-install

      - name: Install xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Install ruby dependencies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.1'
          bundler-cache: true

      - name: Install environment variables
        run: yarn ci-env-vars

      - name: Cache pods
        id: cocoapods-cache
        uses: actions/cache@v3
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install pods
        if: steps.cocoapods-cache.outputs.cache-hit != 'true'
        run: pod install --project-directory=ios

      - name: Deploy iOS
        uses: maierj/fastlane-action@v3.0.0
        with:
          lane: ios deploy app:core method:beta
