name: Deploy Android

on:
  push:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  ANDROID_GOOGLE_KEY: ${{ secrets.ANDROID_GOOGLE_KEY }}
  ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
  ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
  ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
  ANDROID_STORE_FILE_DEBUG: ${{ secrets.ANDROID_STORE_FILE_DEBUG }}
  ANDROID_STORE_FILE_RELEASE: ${{ secrets.ANDROID_STORE_FILE_RELEASE }}
  IOS_APPLE_KEY: ${{ secrets.IOS_APPLE_KEY }}
  MAESTRO_CLOUD_API_KEY: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
  SLACK_URL: ${{ secrets.SLACK_URL }}

jobs:
  deploy-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install node dependencies
        run: yarn ci-install

      - name: Install ruby dependencies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.1'
          bundler-cache: true

      - name: Install android dependencies
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'zulu'
          cache: 'gradle'

      - name: Install environment variables
        run: yarn ci-env-vars

      - name: Deploy android
        uses: maierj/fastlane-action@v3.0.0
        with:
          lane: android deploy app:core method:beta

      - name: Deploy tests
        uses: mobile-dev-inc/action-maestro-cloud@v1.2.3
        with:
          async: true
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          app-file: android/app/build/outputs/apk/release/app-universal-release.apk
