name: Deploy iOS

on:
  push:
    branches: [master]
  pull_request:
    branches: [ios-build]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
  FASTLANE_GIT_TOKEN: ${{ secrets.FASTLANE_GIT_TOKEN }}
  IOS_APPLE_KEY: ${{ secrets.IOS_APPLE_KEY }}
  MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

jobs:
  deploy-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install node dependencies
        run: yarn ci-install

      - name: Install xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Install ruby dependencies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true

      - name: Install environment variables
        run: yarn ci-env-vars

      - name: Install pods
        uses: actions/cache@v2
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
        run: NO_FLIPPER=1 pod install --project-directory=ios

      - name: Deploy iOS
        uses: maierj/fastlane-action@v3.0.0
        with:
          lane: ios deploy app:core method:beta

      - name: Deploy tests
        uses: mobile-dev-inc/action-maestro-cloud@v1.2.3
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          app-file: <app_name>.app
