name: Mobile Dev Action iOS

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
      - run: xcodebuild -project core.xcodeproj -scheme core -destination 'platform=iOS Simulator,name=iPhone 11'
      - uses: mobile-dev-inc/action-maestro-cloud@v1.2.3
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          app-file: <app_name>.app
