name: Validate Code

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  validate-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install modules
        run: pnpm ci-install

      - name: Run prettier
        run: pnpm ci-prettify

      - name: Run code dupe
        run: pnpm ci-dupe

      - name: Run lint
        run: pnpm ci-lint

      - name: Run tests
        run: pnpm ci-test
