name: Validate Code

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  validate-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install node dependencies
        run: yarn ci-install

      - name: Run code dupe
        run: yarn ci-dupe-code

      - name: Run code unused
        run: yarn ci-unused-code

      - name: Run lint
        run: yarn ci-lint

      - name: Run tests
        run: yarn ci-test
